"""add recommendation_items table

Revision ID: a67a62800704
Revises: 7a7dc0d777fc
Create Date: 2026-03-18 20:42:54.295185

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a67a62800704"
down_revision: Union[str, None] = "7a7dc0d777fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_items",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_de", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_en", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason_de", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason_en", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["recommendation_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendation_items_parent_id"),
        "recommendation_items",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_items_type"),
        "recommendation_items",
        ["type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recommendation_items_type"), table_name="recommendation_items"
    )
    op.drop_index(
        op.f("ix_recommendation_items_parent_id"), table_name="recommendation_items"
    )
    op.drop_table("recommendation_items")
    # ### end Alembic commands ###
