"""add matches_item_id and product_bike_types

Revision ID: c222a2b6e5f8
Revises: b2c3d4e5f6a7
Create Date: 2026-03-11 15:07:05.800373

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c222a2b6e5f8"
down_revision: Union[str, None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_bike_types",
        sa.Column("product_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bike_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("product_id", "bike_type"),
    )
    op.add_column(
        "products",
        sa.Column("matches_item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_products_matches_item_id"),
        "products",
        ["matches_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_matches_item_id"), table_name="products")
    op.drop_column("products", "matches_item_id")
    op.drop_table("product_bike_types")
    # ### end Alembic commands ###
